config/routes.rb
Rails.application.routes.draw do
  get "/todos/index"

  match "todos/add" => "todos#add", :via => :post
  

  get "/todos/delete" => "todos#delete", :as => :delete

end

app/models/todo.rb
class Todo < ActiveRecord::Base
attr_accessible :todo_item

validates :todo_item, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
      @todo_items = Todo.all
       @new_todo = Todo.new 
  end


  def delete
   #put delete logic here
  end


def add
   
   
   todo = Todo.create(:todo_item => params[:todo][:todo_item])
   
   if !todo.valid?
        flash[:error] = todo.errors.full_messages.join("<br>").html_safe
    
    else
     flash[:success] = "Todo added successfully"  

   end
   redirect_to :action => 'index'
end


def complete
    params[:todos_checkbox].each do |check|
       todo_id = check
       t = Todo.find_by_id(todo_id)
       #code to update the status here
     end
    redirect_to :action => 'index'
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharedTodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">Just Did it</a>
    </div>
  </div>


<%= yield %>

</body>
</html>

app/views/todos/delete.html.erb
<p>Todo successfully deleted</p>
<a href="/todos/index">Back</a>

app/views/todos/index.html.erb
<title>Shared Todo App </title>

<%= form_tag("/todos/complete/", :method => "post") do %>
<ul style="list-style-type:none;">
<% @todo_items.each do |t| %> 
    <li> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %>  </li>
<%end%>
</ul>
<%= submit_tag("Complete Todos", :class=>"btn btn-success") %>
<%end %>
 
<% if !flash[:error].nil? %>
 <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert" >×</button>
    <strong><%= flash[:error] %></strong>
    </div>
<% end %>

<% if flash[:success] %>
   <div class="alert alert-success">
     #show flash[:success] message here
   </div>
  <% end %>

<p>All your todos here</p>

<title>Shared Todo App </title>
<div class="container">
  <div class="row">
    <div class="span4">
      <h1>Shared Todo App</h1>
      <hr>
      <p>All your todos here</p>
      <div class="well">
        <% @todo_items.each do |t| %>
         <li> <%= t.todo_item %> </li>
        <% end %>
      </div> <!-- well -->
    </div> <!-- span4 -->
  </div> <!-- row -->
</div> <!-- container -->

<%= link_to "Delete last todo", delete_path %>